### PR TITLE
196 fix uploading new files while old files still uploading

### LINKED ISSUE #196: Fix Uploading new files while old files still uploading
Should add to loading courses, instead it replaces loading courses

### PR DESCRIPTION
**Pull request by tim-macphail**
Closes #196 by using a ref to `courses` state to prevent asynchronous updating of courses and race conditions involved with that.

Simplifies the review page quite a bit too. Got rid of use of memo in review page. An O(n) operation where P(n > 10) < 0.01 is not worth the extra technical complexity.

Also, url params never needed to be used, since currentCourse is stored in state already, so I removed them. It still has the same functionality and appearance as before (with routes, and history).

### CODE REVIEW

File: client/src/pages/Review/Review.tsx [hunk 1]
```diff
@@ -1,25 +1,45 @@
...
   Title,
   Subtitle,
 } from "../../components/AppTopBar";
 import CoursePanel from "./CoursePanel";
-
-import testState from "./data";
 import NavigationPanel from "./NavigationPanel";
 
 const Review = () => {
-  const { courseKey: courseKeyUrlParam } = useParams();
```
Comment (cloudyyoung) [inline client/src/pages/Review/Review.tsx:20]: This and all code blocks below relates to _url params_ shouldn't be removed. 

This gives the ability to redirect user to the specific course page if `course_id` is specified in the url.

File: client/src/pages/Review/Review.tsx [hunk 2]
```diff
@@ -36,19 +56,9 @@ const Review = () => {
     onMainMarginLeft();
     window.addEventListener("resize", onMainMarginLeft);
     return () => window.removeEventListener("resize", onMainMarginLeft);
-  }, [navRef.current, mainRef.current, currentCourseKey]);
```
Comment (cloudyyoung) [inline client/src/pages/Review/Review.tsx:39]: `currentCourseKey` or its equivalent variable shouldn't be removed. 

`NavigationPanel` and `MainPanel` might occur display bug when screen is resized and without also monitoring course tab change.

This is a fix to the mentioned bug that was pointed out in a previous PR.

File: client/src/pages/Review/Review.tsx [hunk 3]
```diff
@@ -36,19 +56,9 @@ const Review = () => {
...
-  // and assign value to current course key
   useEffect(() => {
-    if (
-      courseKeyUrlParam === undefined ||
-      courseKeyLookup[courseKeyUrlParam] === undefined
-    ) {
-      setCurrentCourseKey(null);
-    } else {
-      setCurrentCourseKey(courseKeyUrlParam);
-    }
```
Comment (cloudyyoung) [inline client/src/pages/Review/Review.tsx:51]: Relates to previous _url param_ comment. This guards only valid `course_id` in _url params_ is parsed and redirected.

File: client/src/pages/Review/Review.tsx [hunk 4]
```diff
@@ -58,86 +68,35 @@ const Review = () => {
     return () => window.removeEventListener("beforeunload", beforeUnload);
   }, []);
 
-  useEffect(() => {
-    if (currentCourseKey === null) {
-      setTimeout(() => history.pushState(null, "", "/app"), 10);
-    } else {
-      setTimeout(() => history.pushState(null, "", `/app/${currentCourseKey}`), 10);
-    }
-  }, [currentCourseKey]);
```
Comment (cloudyyoung) [inline client/src/pages/Review/Review.tsx:67]: This `useEffect` monitoring changes on `currentCourseKey` so the url is updated as soon as the current course key changes.
 
This is here so that developers don't have to always put `window.history.pushState` under every single `setCurrentCourseKey` statement, because it's repetitive and forgettable.

File: client/src/pages/Review/Review.tsx [hunk 5]
```diff
@@ -58,86 +68,35 @@ const Review = () => {
...
-  );
-
-  // Memorize the course based on the course key
-  const currentCourse = useMemo(
-    () =>
-      currentCourseKey && currentCourseKey in courseKeyLookup
-        ? courseKeyLookup[currentCourseKey]
-        : null,
-    [currentCourseKey, courseKeyLookup[currentCourseKey || ""]]
-  );
```
Comment (cloudyyoung) [inline client/src/pages/Review/Review.tsx:85]: This lookup table is for `currentCourseKey` to quickly find its corresponding `Course` object. 
The table is in the format of `{ key: Course }`. To avoid iterating the `courses` array.

File: client/src/pages/Review/NavigationPanel.tsx [hunk 6]
```diff
@@ -47,25 +47,32 @@ const NavigationPanel = ({
...
+          course.key = `${course.code.toLowerCase()}-${course.number}`;
+
           onCoursesChanged(course);
         })
         .catch((error) => {
           console.log(error);
         })
         .finally(() => {
           setLoading((prev) => prev.filter((f) => f !== file?.name));
+          inputRef.current?.value && (inputRef.current.value = "");
```
Comment (cloudyyoung) [inline client/src/pages/Review/NavigationPanel.tsx:75]: Use `if` when available for better readability.

**Review by cloudyyoung — CHANGES_REQUESTED** [review]

File: client/src/pages/Review/Review.tsx (hunk 1 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:20]: Yes, but this never did anything (except for with the test course) because reloading / redirecting reset app state anyway

File: client/src/pages/Review/Review.tsx (hunk 4 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:67]: I see. What's the timeout for?

File: client/src/pages/Review/Review.tsx (hunk 5 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:85]: Yes but in reality the probability that we have more than 10 courses is very very low, so I don't mind iterating over the array. O(n) effectively becomes O(1)

File: client/src/pages/Review/Review.tsx (hunk 1 above)
Comment (cloudyyoung) [reply client/src/pages/Review/Review.tsx:20]: But this will be useful after the data is persistent in frontend (and PWA)

File: client/src/pages/Review/Review.tsx (hunk 2 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:39]: The bug is no longer reproducible as far as I can tell

File: client/src/pages/Review/Review.tsx (hunk 1 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:20]: True. Are we thinking localStorage for that? I don't know what a good option is

File: client/src/pages/Review/Review.tsx (hunk 4 above)
Comment (cloudyyoung) [reply client/src/pages/Review/Review.tsx:67]: You can remove `timeout` now. It was used to avoid race condition but it doesn't seem to have it anyways.

File: client/src/pages/Review/Review.tsx (hunk 5 above)
Comment (cloudyyoung) [reply client/src/pages/Review/Review.tsx:85]: This was introduced in #118 for improving performance issue (that I never really experience...), so yeah if you're good with removing this then I'm good too, we shall agree that it's the assessment list is _the_ dragon.

File: client/src/pages/Review/Review.tsx (hunk 2 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:39]: Oh, it came back I'll squash it now

File: client/src/pages/Review/Review.tsx (hunk 5 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:85]: Yeah I do believe there is an issue somewhere but not here

File: client/src/pages/Review/Review.tsx (hunk 2 above)
Comment (cloudyyoung) [reply client/src/pages/Review/Review.tsx:39]: Even better! Then remove it

File: client/src/pages/Review/Review.tsx (hunk 1 above)
Comment (tim-macphail) [reply client/src/pages/Review/Review.tsx:20]: https://reactrouter.com/en/main/hooks/use-before-unload looks good

**Review by cloudyyoung — APPROVED** [review]
